- back/src/main/java/com/mainproject/back/language/entity/Language.java
- back/src/main/java/com/mainproject/back/member/entity/Member.java
- back/src/main/java/com/mainproject/back/member/language/MemberLanguage.java
- back/src/main/java/com/mainproject/back/member/tag/MemberTag.java
- library entity 완성
- member entity 수정
> Be feat/language entity jin

- back/src/main/java/com/mainproject/back/BackApplication.java
- back/src/main/java/com/mainproject/back/ban/entity/Ban.java
- back/src/main/java/com/mainproject/back/follow/entity/Follow.java
- back/src/main/java/com/mainproject/back/language/entity/Language.java
- back/src/main/java/com/mainproject/back/letter/entity/Letter.java
- back/src/main/java/com/mainproject/back/member/entity/Member.java
- back/src/main/java/com/mainproject/back/member/language/MemberLanguage.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/member/tag/MemberTag.java
- back/src/main/java/com/mainproject/back/tag/entity/Tag.java
- back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
- back/src/main/resources/application.yml
- 연관관계 구현
- application.yml 수정
- 엔티티 어노테이션 수정
> Be feat/entity mapping ming

- back/build.gradle
- back/src/main/java/com/mainproject/back/helper/UriCreator.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
- back/src/main/java/com/mainproject/back/member/entity/Member.java
- back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- back/src/main/resources/application.yml
> feat : member Crud_gri

- back/src/main/java/com/mainproject/back/exception/BusinessLogicException.java
- back/src/main/java/com/mainproject/back/exception/ExceptionCode.java
- back/src/main/java/com/mainproject/back/exception/advice/ErrorResponse.java
- back/src/main/java/com/mainproject/back/exception/advice/GlobalExceptionAdvice.java
- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterPostDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterResponseDto.java
- back/src/main/java/com/mainproject/back/letter/entity/Letter.java
- back/src/main/java/com/mainproject/back/letter/exception/LetterExceptionCode.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/letter/repository/LetterRepository.java
- back/src/main/java/com/mainproject/back/letter/service/LetterService.java
- back/src/main/java/com/mainproject/back/util/UriCreator.java
letter 추가, 특정 letter 조회
exception advice 추가
> feat: letter 조회 추가 + exception

- back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
- back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
- back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
- back/src/main/java/com/mainproject/back/vocabulary/exception/VocabExceptionCode.java
- back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
- back/src/main/java/com/mainproject/back/vocabulary/repository/VocabRepository.java
- back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
vocabulary 추가 / 편집 / 조회 / 삭제 기능 구현
> Be feat/vocabulary jin

- front/package-lock.json
- front/package.json
- axios 라이브러리 추가
- swiper 라이브러리 추가
> chore: axios, swiper 패키지 추가

- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
- back/src/main/java/com/mainproject/back/member/entity/Member.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
> feat : Member_Post_회원가입시_멤버상태_변경로직_구현_gri

- .idea/aws.xml
- .idea/jpa-buddy.xml
- back/.gitignore
- back/src/main/java/com/mainproject/back/exception/advice/GlobalExceptionAdvice.java
- back/src/main/java/com/mainproject/back/init/InitDB.java
- back/src/main/java/com/mainproject/back/init/TagInit.java
- back/src/main/java/com/mainproject/back/language/entity/Language.java
- back/src/main/java/com/mainproject/back/language/repository/LanguageRepository.java
- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterCountDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterListDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterPostDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterResponseDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterSimpleDto.java
- back/src/main/java/com/mainproject/back/letter/entity/Letter.java
- back/src/main/java/com/mainproject/back/letter/entity/Nations.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/letter/repository/LetterRepository.java
- back/src/main/java/com/mainproject/back/letter/service/LetterService.java
- back/src/main/java/com/mainproject/back/member/dto/MemberLetterDto.java
- back/src/main/java/com/mainproject/back/member/dto/MemberSimpleDto.java
- back/src/main/java/com/mainproject/back/member/entity/Member.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/tag/entity/Tag.java
- back/src/main/java/com/mainproject/back/tag/repository/TagRepository.java
- back/src/test/java/com/mainproject/back/letter/repository/LetterRepositoryTest.java
- tag, language 디비에 미리 저장
- letter 추가 로직 구현
> Be feat/letter ming

- front/src/App.tsx
- front/src/components/Common/LetterStatusIcon/LetterStatusIcon.tsx
- front/src/components/Common/UserCard/UserCard.module.scss
- front/src/components/Common/UserCard/UserCard.tsx
- front/src/components/Following/Following.module.scss
- front/src/components/Following/Following.tsx
- front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
- front/src/components/Letter/LetterWrapper/LetterWrapper.tsx
- front/src/pages/FollowingPage.tsx
- front/src/utils/types/letter/user.type.ts
- 기존의 편지 유저 리스트와 비슷한 구조
- 카드 클릭 시, 유저 프로필 페이지로 이동
- 마우스 호버 시, 커서가 포인터가 되도록 수정
> Fe feat/following 친구 목록 페이지

- front/src/App.tsx
- front/src/components/BlackList/BlackList.module.scss
- front/src/components/BlackList/BlackList.tsx
- front/src/components/Common/UserCard/UserCard.tsx
- front/src/components/Following/Following.tsx
- front/src/dummy/userList.ts
- front/src/pages/BlackListPage.tsx
- front/src/utils/types/users/user.type.ts
- 삭제 버튼 클릭 시, 임시 핸들러
- 카드 클릭 시, 해당 유저 프로필 페이지로 이동
> Fe feat/black list ayo #58

- back/src/main/java/com/mainproject/back/init/InitDB.java
- back/src/main/java/com/mainproject/back/language/dto/MemberLanguageDto.java
- back/src/main/java/com/mainproject/back/language/entity/Language.java
- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterListDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterPostDto.java
- back/src/main/java/com/mainproject/back/letter/dto/LetterResponseDto.java
- back/src/main/java/com/mainproject/back/letter/entity/Letter.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
- back/src/main/java/com/mainproject/back/member/dto/MemberSearchDto.java
- back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- back/src/main/java/com/mainproject/back/tag/dto/TagSimpleDto.java
- back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
- back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
- back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
- back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
멤버 태그로 검색 구현
location/nation 구분
letter에 hasPic 추가
> feat: 멤버 태그 검색 구현

- front/src/App.tsx
- front/src/components/Profile/ProfilePage.tsx
- front/src/utils/types/common/index.ts
- front/src/utils/types/index.ts
- type common 에 defaultProps  파일 export 추가
- 프로플 상세 페이지 및 라우터 컴포넌트 생성
> feat: common type export 파일 추가 & profile 상세 페이지 라우터 및 컴포넌트 생성성

- back/src/main/java/com/mainproject/back/audit/Auditable.java
- back/src/main/java/com/mainproject/back/block/controller/BlockController.java
- back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
- back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
- back/src/main/java/com/mainproject/back/follow/service/FollowService.java
- back/src/main/java/com/mainproject/back/letter/entity/Letter.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
- back/src/main/java/com/mainproject/back/member/dto/MemberSearchDto.java
- back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- back/src/main/java/com/mainproject/back/tag/entity/MemberTag.java
- back/src/main/java/com/mainproject/back/tag/entity/Tag.java
- back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
- 태그로 검색 시 본인 제외, 추천 친구에 이미 친구인 사람 제외
- 태그 검색, 멤버 정보 조회에 친구인지 아닌지 boolean 값 추가
- Letter의 pic -> photoUrl
- 모든 엔티티에 Auditable 추가(lastModifiedAt -> updatedAt)
> fix: 기능 부가사항 수정

- front/src/components/Common/UserCard/UserCard.tsx
- front/src/components/Letter/LetterList.tsx
- front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
- front/src/components/Letter/LetterWrapper/LetterWrapper.tsx
- front/src/recoil/atoms/index.ts
- front/src/recoil/atoms/letter/index.ts
- front/src/recoil/atoms/letter/letter.ts
Closes #77 
편지를 교환한 적이 있던 유저 리스트에서 유저 클릭 시, 해당 유저 정보를 리코일에 저장하도록 로직을 변경했습니다.
> feat: 편지 목록에서 편지 클릭 로직에 리코일 추가

- .gitignore
- front/package-lock.json
- front/package.json
- front/src/utils/axios/fetch.ts
- front/src/utils/axios/index.ts
- front/src/utils/axios/instanse.ts
> axios 설정 merge 

- front/src/components/Main/RecomandUser/RecomandUserList.tsx
> [FE] fix: 메인 swiper 슬라이더 버그 수정

- front/src/components/Common/LetterStatusIcon/LetterStatusIcon.tsx
- front/src/components/Letter/LetterList.tsx
- front/src/components/Search/SearchList/SearchList.tsx
- 버튼이 너무 작아서 클릭 미스가 나는 현상을 수정하기 위한 마크업 변경
> style: 마크업 구조 변경

- front/src/App.tsx
- front/src/components/LetterDetail/LetterDetailWrapper.tsx
- front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.module.scss
- front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.tsx
- front/src/components/Main/RecomandUser/RecomandUserList.tsx
- front/src/components/PictureModal/PictureModal.module.scss
- front/src/components/PictureModal/PictureModal.tsx
- front/src/dummy/letter.ts
- front/src/index.css
- front/src/recoil/atoms/letter/letter.ts
- front/src/utils/types/letter/letter.type.ts
- Swiper import문을 App.tsx로 전부 이동
- 편지 조회 시, 이미지 확대 기능
> [FE] 편지 조회 이미지 확대 모달

- front/src/utils/axios/instanse.ts
> feat: instance 디폴트 설정

- front/package-lock.json
- front/package.json
- front/src/components/Login/LoginMain.tsx
- front/src/utils/axios/instanse.ts
- front/src/utils/cookie/index.ts
> Fe feat/login auth wan

- front/src/components/Common/Button/Button.module.scss
- front/src/components/Common/Button/Button.tsx
- front/src/components/Common/Modal/AlertModal.module.scss
- front/src/components/Common/Modal/FullPageModal.tsx
- front/src/components/Common/ProfileImage/ProfileImage.tsx
- front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
- front/src/components/MyProfile/MyProfile.tsx
- front/src/components/MyProfile/MyProfileImage.tsx
- front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
- front/src/components/Profile/Profile.tsx
- front/src/index.css
- front/src/recoil/atoms/user/user.ts
- front/src/recoil/atoms/user/userLanguage.ts
- front/src/recoil/atoms/user/userLocation.ts
- front/src/utils/common/index.ts
- memeber id로 상세 정보 출력
- 친구 추가 기능 적용
- 친구 해제 기능 보류 (API 수정 대기)
- 친구 차단 기능 추가 
- 차단 확인 모달 창 띄우기
- 친구 차단 해제 기능 보류 (API 수정 대기)
> [FE] feat: 회원 상세 조회 API 작업

- back/src/main/java/com/mainproject/back/block/controller/BlockController.java
- back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
- back/src/main/java/com/mainproject/back/block/service/BlockService.java
- back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
- back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
- back/src/main/java/com/mainproject/back/follow/service/FollowService.java
- back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
- back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
- back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- fix: delete follow/block targetId로 삭제
- fix: patch member tags/languages 수정
- fix: member 조회 시 introduce, block 추가
> Be fix/hotfix ming

- front/src/components/Login/LoginMain.tsx
- front/src/components/SignUp/SignUpMain.tsx
- front/src/utils/signup/function.ts
1. 회원가입 api 설정 완료
2. login 페이지 수정 완료
3. 회원가입/ login 모달창 적용
4. 벡엔드 유효성과 동일하게 비밀번호 유효성검사 수정
> feat:회원가입 api완료

- front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
- front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
- front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
- front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
- front/src/components/MyProfile/MyProfile.tsx
- front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
> fix: 마이프로필 페이지 api 버그 수정중

- front/src/App.tsx
- front/src/components/BlackList/BlackList.tsx
- front/src/components/Common/Empty/Empty.module.scss
- front/src/components/Common/LetterStatusIcon/LetterStatusIcon.tsx
- front/src/components/Common/UserCard/UserCard.tsx
- front/src/components/Common/UserCard/UserCardInfo/UserCardInfo.tsx
- front/src/components/Following/Following.tsx
- front/src/components/Layouts/BaseLayout.tsx
- front/src/components/Layouts/NoneLayout.tsx
- front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
- front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
- front/src/components/MyProfile/MyProfile.tsx
- front/src/components/MyProfile/MyProfileImage.tsx
- front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
- front/src/components/Profile/Profile.module.scss
- front/src/components/Profile/Profile.tsx
- front/src/components/SignUp/SignUpMain.tsx
- front/src/components/Start/Start.tsx
- front/src/context/AuthContext.tsx
- front/src/index.scss
- front/src/recoil/atoms/user/user.ts
- front/src/utils/axios/instanse.ts
- front/src/utils/common/index.ts
- front/src/utils/types/users/user.type.ts
[팔로잉 친구 목록]
- 리스트 상단 차단친구 목록 버튼 추가 (마이프로필에도 추후 추가)
- 주고받은 편지 상태에 따른 status 아이콘 노출 조건 처리
[프로필 상세]
- 친구 상세 프로필에 편자 작성 버튼 추가
> [FE] feat:팔로잉 친구 목록 리스트 API 작업

- back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/tag/controller/TagController.java
- back/src/main/java/com/mainproject/back/util/RequestFilter.java
- back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
- back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
[BE] 로그response값 , nation 제외 , 단어post시 response
> [BE] 로그response값 , nation 제외 , 단어post시 response

- front/src/components/Intro/Intro.tsx
- front/src/components/Login/Login.tsx
구글 오어스 기능 구현 완
-로직
구글 로그인 버튼클릭시 백엔드 url로 이동 -> 구글로그인 페이지
->로그인 성공시 / 페이지이동 -> url 파싱해서 토큰 쿠키에저장 -> 
/members 요청해서 구글로그인 사용자 location값 없으면 /start 있으면 /main이동
> feat:구글 오어스 기능 완료

- front/src/components/LetterDetail/LetterDetailWrapper.module.scss
- front/src/components/LetterDetail/LetterDetailWrapper.tsx
셀렉트 창으로 번역하고싶은 언어 선택후, 파파고 번역 클릭시 편지내용 번역돼서 랜더링
> feat:편지번역기능 완료

- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/letter/service/LetterService.java
- 현재 로그인한 사용자가 보낸 편지는 잠금 걸리지 않음
> Be fix/letter sender ming

- front/src/components/BlackList/BlackList.tsx
- front/src/components/Following/Following.tsx
- front/src/components/Letter/LetterList/LetterList.tsx
- front/src/components/Letter/LetterUserList/LetterUserList.tsx
- front/src/components/LetterDetail/LetterDetailWrapper.tsx
- front/src/components/LetterDetail/NewLetterWrapper.tsx
- front/src/components/Main/MainLetters/MainLetter.tsx
- front/src/components/Main/RecomandUser/RecomandUserList.tsx
- front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
- front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
- front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
- front/src/components/MyProfile/MyProfile.tsx
- front/src/components/MyProfile/MyProfileImage.tsx
- front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
- front/src/components/Profile/Profile.tsx
- front/src/components/Search/SearchList/SearchList.tsx
- front/src/components/SignUp/SignUpMain.tsx
- front/src/context/AuthContext.tsx
- front/src/recoil/selectors/search/search.ts
- front/src/recoil/selectors/user/user.ts
- front/src/recoil/selectors/user/userLanguage.ts
- front/src/recoil/selectors/user/userLocation.ts
- front/src/recoil/selectors/user/userTag.ts
- front/src/utils/axios/fetch.ts
> [FE] API URL 변경

- front/src/App.tsx
- front/src/components/Letter/LetterList/LetterList.tsx
Reverts codestates-seb/seb42_main_002#191
> Revert "[FE] 프론트엔드 배포"

- front/src/App.tsx
- front/src/components/Letter/LetterList/LetterList.tsx
Reverts codestates-seb/seb42_main_002#193
리버트를 다시 리버트...
> Revert "Revert "[FE] 프론트엔드 배포""

- front/src/components/Profile/Profile.tsx
- front/src/components/Voca/Voca.tsx
- 오타 수정
- 단어가 빈 화면에서도 단어 추가 버튼이 나오도록 수정
> [FE-FIX] 친구 추가 API 오탈자 수정 & 단어 추가 버튼 추가

- back/src/main/java/com/mainproject/back/block/mapper/BlockMapper.java
- back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
- back/src/main/java/com/mainproject/back/follow/mapper/FollowMapper.java
- back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
- back/src/main/java/com/mainproject/back/letter/exception/LetterExceptionCode.java
- back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
- back/src/main/java/com/mainproject/back/letter/service/LetterService.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/dto/MemberLetterDto.java
- back/src/main/java/com/mainproject/back/member/dto/MemberLetterInterface.java
- back/src/main/java/com/mainproject/back/member/dto/MemberSimpleDto.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
- member 조회 리스폰스에 memberStatus 추가
- 추천친구 / 태그,언어 검색 / 차단조회 / 내 친구조회에서 Active 한 member만 조회 할 수 있게 수정
- 탈퇴, 휴면계정한테 편지 못보내게 수정
> fix/멤버 탈퇴시 조회기능 수정

- front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
- front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
- front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
- 언어 및 태그 하나이상 선택하게 하는 유효성 체크 추가 -> toast 에러 노출
> [FE] fix: #188 언어 및 태그 선택 유효성 체크 추가

- back/src/main/java/com/mainproject/back/exception/CommonExceptionCode.java
- back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
- back/src/main/java/com/mainproject/back/language/controller/LanguageController.java
- back/src/main/java/com/mainproject/back/language/dto/LanguageSimpleDto.java
- back/src/main/java/com/mainproject/back/language/repository/LanguageRepository.java
- back/src/main/java/com/mainproject/back/language/service/LanguageService.java
- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/member/controller/MemberController.java
- back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
- back/src/main/java/com/mainproject/back/member/service/MemberService.java
- back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
- back/src/main/java/com/mainproject/back/vocabulary/repository/VocabRepository.java
- 친구 전체 조회 수정
- 언어 전체 조회 추가
- 추천 친구 수정
- 로그인시 멤버 상태 체크 추가
> Be fix/member quit ming

- front/src/components/LetterDetail/NewLetterWrapper.tsx
- front/src/components/MyProfile/MyProfileImage.tsx
- front/src/utils/image/index.ts
- package-lock.json
- package.json
- 이미지 업로드시 파일 확장자 및 용량 체크 utils 함수작성
- 이미지 압축 라이브러리 설치 browser-image-compression
=> 우선 간단하게 적용하였는데 추후에 차라리 multer 라이브러리로 교체하는게 나은 것 같기도 합니다 -> 서버
```
/**
*  이미지 용량  체크
*/
const LIMIT_SIZE = 1024 ** 5; // 5MB
const checkUploadsSize = async (event: React.ChangeEvent<HTMLInputElement>) => {
const compressedFile = await imageCompress(event);
if (compressedFile && compressedFile.size > LIMIT_SIZE) {
toast.error('파일 용량은 5MB 이하만 가능합니다');
return;
}
return true;
};
```
```
/**
* 이미지 확장자 체크
* @param event
* @returns
*/
const EXTEND_FILE = ['image/jpeg', 'image/png'];
const checkUploadsExtendName = (event: React.ChangeEvent<HTMLInputElement>) => {
if (
event.target.files &&
event.target.files[0].type &&
!EXTEND_FILE.includes(event.target.files[0].type)
) {
toast.error('jpg, jpeg, png 파일만 가능합니다'); …
```
> [FE] #204 이미지 업로드 파일 확장자 & 용량 유효성 체크 함수 작성

- front/src/components/Common/Button/ButtonGroup.module.scss
- front/src/components/Common/Button/ButtonGroup.tsx
- front/src/components/Following/Following.tsx
- front/src/components/Profile/Profile.module.scss
- front/src/components/Search/SearchHeader/SearchHeader.tsx
- front/src/components/Voca/Voca.module.scss
- front/src/components/Voca/VocaModal/VocaModal.module.scss
- front/src/components/Voca/VocaModal/VocaModal.tsx
- 단어장 설명 글자 수 유효성 체크
- 단어장 모달 창 넓이 및 input css 수정
- 단어장 추가 및 편지작성 원형 버튼 position 수정
- 검색 필터 icon 위치 수정 (왼쪽 통일) -> 텍스트도 필터로만 줄여서 작은사이즈에서 공간확보하는것도 좋을 것 같습니다
> [FE] 단어장 모달 창 및 단어장 추가버튼 및 편지 작성 버튼 CSS 수정

- front/src/components/Profile/Profile.tsx
- 내가 선택한 언어 및 태그와 일치하는 라벨 활성화 표시 추가
> [FE] feat:친구 프로필에서 내가 선택한 언어 및 태그 활성화 표시 추가

- back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
- back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
- back/src/main/java/com/mainproject/back/follow/service/FollowService.java
- back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
- back/src/main/java/com/mainproject/back/letter/exception/LetterExceptionCode.java
- back/src/main/java/com/mainproject/back/letter/repository/LetterRepository.java
- back/src/main/java/com/mainproject/back/letter/service/LetterService.java
- back/src/main/java/com/mainproject/back/member/dto/FollowMemberInterface.java
- back/src/main/java/com/mainproject/back/member/dto/MemberLetterInterface.java
- back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
> Be fix/is read ming

- front/src/App.tsx
> fix: Suspense 위치 수정

- front/src/components/LetterDetail/LetterContent/NewLetterContent.module.scss
- front/src/components/Voca/VocaCard/VocaCard.module.scss
- front/src/components/Voca/VocaCard/VocaCard.tsx
- front/src/components/Voca/VocaModal/VocaModal.module.scss
- textarea line-height 추가
- 단어장 리스트 내용 더보기 css 수정 -> 기존 클릭 가능 여부를 알 수 없는 부분 개선
> [FE] fix: 단어장 의미 더보기 css 부분 수정

- front/src/components/LetterDetail/LetterContent/NewLetterContent.tsx
- front/src/components/Search/SearchList/SearchList.tsx
- 글 작성 중 페이지 이동 시, 작성 중인 내용 초기화
- 검색창에서 편지 보내지 못하는 오류 수정
> [Fe] fix: 글 작성 중 페이지 이동 시 초기화 / 검색창에서 편지 보내지 못하는 오류 수정

- front/src/components/MyProfile/MyProfile.tsx
> [FE] fix: 스타일 가이드 버튼 제거
